import { network } from "hardhat";
import { mkdir, readFile, writeFile } from "node:fs/promises";

type DeployedAddresses = {
  USDC: string;
  TREASURY: string;
  COMMIT: string;
  LENDER: string;
  ZKVER: string;
  WORLDID_VERIFIER: string;
  VAULT: string;
  ROUTER: string;
  AMM_ADDR: string;
};

const ERC20_ABI = [
  "function balanceOf(address account) view returns (uint256)",
  "function allowance(address owner, address spender) view returns (uint256)",
  "function approve(address spender, uint256 amount) returns (bool)",
] as const;

async function writeAddressFiles(addresses: DeployedAddresses) {
  const smartcontractAddresses = `// auto-generated by deploy.ts - do not edit manually

export const ADDR = {
  USDC: "${addresses.USDC}",
  TREASURY: "${addresses.TREASURY}",
  COMMIT: "${addresses.COMMIT}",
  LENDER: "${addresses.LENDER}",
  ZKVER: "${addresses.ZKVER}",
  WORLDID_VERIFIER: "${addresses.WORLDID_VERIFIER}",
  VAULT: "${addresses.VAULT}",
  AMM_ADDR: "${addresses.AMM_ADDR}",
  ROUTER: "${addresses.ROUTER}"
} as const;
`;

  const frontendContracts = `// auto-generated by deploy.ts - do not edit manually
export const CONTRACTS = {
  USDC: "${addresses.USDC}" as \`0x\${string}\`,
  TREASURY: "${addresses.TREASURY}" as \`0x\${string}\`,
  COMMIT: "${addresses.COMMIT}" as \`0x\${string}\`,
  LENDER: "${addresses.LENDER}" as \`0x\${string}\`,
  ZKVER: "${addresses.ZKVER}" as \`0x\${string}\`,
  WORLDID_VERIFIER: "${addresses.WORLDID_VERIFIER}" as \`0x\${string}\`,
  VAULT: "${addresses.VAULT}" as \`0x\${string}\`,
  ROUTER: "${addresses.ROUTER}" as \`0x\${string}\`,
  AMM: "${addresses.AMM_ADDR}" as \`0x\${string}\`,
} as const;
`;

  const smartcontractPath = new URL("./addresses.ts", import.meta.url);
  const frontendPath = new URL("../../frontend/src/config/contracts.ts", import.meta.url);
  const subgraphPath = new URL("../../subgraph/subgraph.yaml", import.meta.url);

  await mkdir(new URL(".", frontendPath), { recursive: true });
  await writeFile(smartcontractPath, smartcontractAddresses);
  await writeFile(frontendPath, frontendContracts);

  let subgraphYaml = await readFile(subgraphPath, "utf8");
  subgraphYaml = subgraphYaml
    .replace(
      /(name: CrowdVault[\s\S]*?source:\s*\n\s*address: ")[^"]*(")/,
      `$1${addresses.VAULT}$2`
    )
    .replace(
      /(name: CommitmentAMM[\s\S]*?source:\s*\n\s*address: ")[^"]*(")/,
      `$1${addresses.AMM_ADDR}$2`
    );
  await writeFile(subgraphPath, subgraphYaml);
}

async function main() {
  const { ethers, networkName } = await network.connect();
  console.log("Network:", networkName);

  const [deployer] = await ethers.getSigners();
  const deployerAddr = await deployer.getAddress();
  console.log("Deployer:", deployerAddr);

  // 1) Sepolia USDC
  const USDC = "0x1c7D4B196Cb0C7B01d743Fbc6116a902379C7238";
  console.log("USDC (Sepolia):", USDC);

  const TREASURY = process.env.TREASURY_ADDRESS?.trim() || deployerAddr;
  if (!/^0x[a-fA-F0-9]{40}$/.test(TREASURY)) {
    throw new Error("Invalid TREASURY_ADDRESS in smartcontract/.env.");
  }
  console.log("Treasury:", TREASURY);

  // 2) MockLender — deterministic lender for manual yield seeding
  const existingLender = process.env.LENDER_ADDRESS?.trim();
  let LENDER: string;
  if (existingLender && /^0x[a-fA-F0-9]{40}$/.test(existingLender)) {
    LENDER = existingLender;
    console.log("MockLender (preserved):", LENDER);
  } else {
    const MockLender = await ethers.getContractFactory("MockLender");
    const lender = await MockLender.deploy(USDC);
    await lender.waitForDeployment();
    LENDER = await lender.getAddress();
    console.log("MockLender (new):", LENDER);
  }

  // 3) MockZKVerifier — simulates KYC; call setKyc(address, true) to approve a user
  const MockZKVerifier = await ethers.getContractFactory("MockZKVerifier");
  const zkVerifier = await MockZKVerifier.deploy();
  await zkVerifier.waitForDeployment();
  const ZKVER = await zkVerifier.getAddress();
  console.log("MockZKVerifier:", ZKVER);
  // KYC-approve the deployer so they can invest in KYC-gated projects
  await (await zkVerifier.setKyc(deployerAddr, true)).wait();
  console.log("Deployer KYC approved in MockZKVerifier");

  // 3b) WorldIDVerifierAdapter — wraps Worldcoin World ID Router on Sepolia.
  //     Investors with a real World ID proof can pass it to invest() for sybil resistance.
  //     Empty proof ("0x") still works for all users — this is purely opt-in.
  const WORLDID_ROUTER = "0x469449f251692E0779667583026b5A1E99512157";
  const worldIdAppId = process.env.WORLDID_APP_ID?.trim() || "app_crowdfundingds_staging";
  const worldIdActionId = process.env.WORLDID_ACTION_ID?.trim() || "invest";
  const WorldIDVerifierAdapter = await ethers.getContractFactory("WorldIDVerifierAdapter");
  const worldIdVerifier = await WorldIDVerifierAdapter.deploy(WORLDID_ROUTER, worldIdAppId, worldIdActionId);
  await worldIdVerifier.waitForDeployment();
  const WORLDID_VERIFIER = await worldIdVerifier.getAddress();
  console.log("WorldIDVerifierAdapter:", WORLDID_VERIFIER);
  console.log("  app_id:", worldIdAppId, "| action_id:", worldIdActionId);

  // 4) CommitmentToken
  const CommitmentToken = await ethers.getContractFactory("CommitmentToken");
  const commit = await CommitmentToken.deploy(deployerAddr, "Nest Token", "NST");
  await commit.waitForDeployment();
  const COMMIT = await commit.getAddress();
  console.log("CommitmentToken:", COMMIT);

  // 5) CrowdVault
  const Vault = await ethers.getContractFactory("CrowdVault");
  const vault = await Vault.deploy(USDC, COMMIT);
  await vault.waitForDeployment();
  const VAULT = await vault.getAddress();
  console.log("CrowdVault:", VAULT);

  // 6) RevenueRouter
  const Router = await ethers.getContractFactory("RevenueRouter");
  const router = await Router.deploy(USDC, TREASURY, 1000); // 10% to backers
  await router.waitForDeployment();
  const ROUTER = await router.getAddress();
  console.log("RevenueRouter:", ROUTER);

  // 7) CommitmentAMM
  const AMM = await ethers.getContractFactory("CommitmentAMM");
  const amm = await AMM.deploy(USDC, COMMIT, VAULT);
  await amm.waitForDeployment();
  const AMM_ADDR = await amm.getAddress();
  console.log("CommitmentAMM:", AMM_ADDR);

  // Wire everything
  await (await commit.setMinter(VAULT)).wait();
  await (await vault.setLender(LENDER)).wait();
  await (await vault.addZK(ZKVER)).wait();
  await (await vault.addZK(WORLDID_VERIFIER)).wait(); // real World ID proofs also accepted
  await (await vault.setRevenueRouter(ROUTER)).wait();
  await (await vault.setAMM(AMM_ADDR)).wait();
  await (await vault.setReleaseFeeBps(100)).wait(); // 1% release fee
  console.log("All modules wired");

  const usdc = await ethers.getContractAt(ERC20_ABI, USDC);
  const usdcBalance = await usdc.balanceOf(deployerAddr);
  console.log("Deployer USDC balance:", ethers.formatUnits(usdcBalance, 6));
  console.log("No demo or seeded projects created by deploy.ts.");

  const addresses = {
    USDC,
    TREASURY,
    COMMIT,
    LENDER,
    ZKVER,
    WORLDID_VERIFIER,
    VAULT,
    ROUTER,
    AMM_ADDR,
  };

  await writeAddressFiles(addresses);
  console.log("\n=== DEPLOYED ADDRESSES ===");
  console.log(addresses);
  console.log("Address files updated (smartcontract, frontend, subgraph)");
}

main().catch((e) => {
  console.error(e);
  process.exit(1);
});
