import { network } from "hardhat";
import { mkdir, readFile, writeFile } from "node:fs/promises";
import { ADDR } from "./addresses.js";

type AddressBook = {
  USDC: string;
  TREASURY: string;
  COMMIT: string;
  LENDER: string;
  VAULT: string;
  AMM_ADDR: string;
  ROUTER: string;
};

function requiredAddress(name: string): string {
  const value = process.env[name]?.trim();
  if (!value || !/^0x[a-fA-F0-9]{40}$/.test(value)) {
    throw new Error(`Missing or invalid ${name}. Add a real deployed address to smartcontract/.env.`);
  }
  return value;
}

async function writeAddressFiles(addresses: AddressBook) {
  const smartcontractAddresses = `// auto-generated by wire-real-modules.ts - do not edit manually

export const ADDR = {
  USDC: "${addresses.USDC}",
  TREASURY: "${addresses.TREASURY}",
  COMMIT: "${addresses.COMMIT}",
  LENDER: "${addresses.LENDER}",
  VAULT: "${addresses.VAULT}",
  AMM_ADDR: "${addresses.AMM_ADDR}",
  ROUTER: "${addresses.ROUTER}"
} as const;
`;

  const frontendContracts = `// auto-generated by wire-real-modules.ts - do not edit manually
export const CONTRACTS = {
  USDC: "${addresses.USDC}" as \`0x\${string}\`,
  TREASURY: "${addresses.TREASURY}" as \`0x\${string}\`,
  COMMIT: "${addresses.COMMIT}" as \`0x\${string}\`,
  LENDER: "${addresses.LENDER}" as \`0x\${string}\`,
  VAULT: "${addresses.VAULT}" as \`0x\${string}\`,
  ROUTER: "${addresses.ROUTER}" as \`0x\${string}\`,
  AMM: "${addresses.AMM_ADDR}" as \`0x\${string}\`,
} as const;
`;

  const smartcontractPath = new URL("./addresses.ts", import.meta.url);
  const frontendPath = new URL("../../frontend/src/config/contracts.ts", import.meta.url);
  const subgraphPath = new URL("../../subgraph/subgraph.yaml", import.meta.url);

  await mkdir(new URL(".", frontendPath), { recursive: true });
  await writeFile(smartcontractPath, smartcontractAddresses);
  await writeFile(frontendPath, frontendContracts);

  let subgraphYaml = await readFile(subgraphPath, "utf8");
  subgraphYaml = subgraphYaml
    .replace(
      /(name: CrowdVault[\s\S]*?source:\s*\n\s*address: ")[^"]*(")/,
      `$1${addresses.VAULT}$2`
    )
    .replace(
      /(name: CommitmentAMM[\s\S]*?source:\s*\n\s*address: ")[^"]*(")/,
      `$1${addresses.AMM_ADDR}$2`
    );
  await writeFile(subgraphPath, subgraphYaml);
}

async function main() {
  const { ethers, networkName } = await network.connect();
  console.log("Network:", networkName);
  console.log("Vault:", ADDR.VAULT);

  const lender = requiredAddress("REAL_LENDER_ADDRESS");

  const vault = await ethers.getContractAt("CrowdVault", ADDR.VAULT);

  console.log("Current lender:", await vault.lender());
  console.log("Current AMM:", await vault.amm());

  if ((await vault.lender()).toLowerCase() !== lender.toLowerCase()) {
    await (await vault.setLender(lender)).wait();
    console.log("Lender wired:", lender);
  }

  if ((await vault.amm()).toLowerCase() !== ADDR.AMM_ADDR.toLowerCase()) {
    await (await vault.setAMM(ADDR.AMM_ADDR)).wait();
    console.log("AMM wired:", ADDR.AMM_ADDR);
  }

  await writeAddressFiles({
    ...ADDR,
    LENDER: lender,
  });
  console.log("Address files updated.");
  console.log("Real modules connected.");
}

main().catch((error) => {
  console.error(error);
  process.exit(1);
});
