export const AMM_ABI = [
  { name: "isAdmin",            type: "function", stateMutability: "view",        inputs: [{ name: "user", type: "address" }],                                                       outputs: [{ type: "bool"    }] },
  { name: "admin",              type: "function", stateMutability: "view",        inputs: [],                                                                                         outputs: [{ type: "address" }] },
  { name: "pendingAdmin",       type: "function", stateMutability: "view",        inputs: [],                                                                                         outputs: [{ type: "address" }] },
  { name: "poolUsdc",           type: "function", stateMutability: "view",        inputs: [{ name: "projectId", type: "uint256" }],                                                                          outputs: [{ type: "uint256" }] },
  { name: "poolCommit",         type: "function", stateMutability: "view",        inputs: [{ name: "projectId", type: "uint256" }],                                                                          outputs: [{ type: "uint256" }] },
  { name: "seeded",             type: "function", stateMutability: "view",        inputs: [{ name: "projectId", type: "uint256" }],                                                                          outputs: [{ type: "bool"    }] },
  { name: "feeBps",             type: "function", stateMutability: "view",        inputs: [],                                                                                                                 outputs: [{ type: "uint256" }] },
  { name: "setFee",             type: "function", stateMutability: "nonpayable",  inputs: [{ name: "feeBps_", type: "uint256" }],                                                                              outputs: [] },
  { name: "transferAdmin",      type: "function", stateMutability: "nonpayable",  inputs: [{ name: "newAdmin", type: "address" }],                                                                             outputs: [] },
  { name: "seedFromVault",      type: "function", stateMutability: "nonpayable",  inputs: [{ name: "projectId", type: "uint256" }, { name: "usdcIn", type: "uint256" }, { name: "commitIn", type: "uint256" }], outputs: [] },
  { name: "swapUsdcForCommit",  type: "function", stateMutability: "nonpayable",  inputs: [{ name: "projectId", type: "uint256" }, { name: "usdcIn",    type: "uint256" }, { name: "minCommitOut", type: "uint256" }], outputs: [{ type: "uint256" }] },
  { name: "swapCommitForUsdc",  type: "function", stateMutability: "nonpayable",  inputs: [{ name: "projectId", type: "uint256" }, { name: "commitIn",  type: "uint256" }, { name: "minUsdcOut",   type: "uint256" }], outputs: [{ type: "uint256" }] },
  /* ─── events ─── */
  {
    name: "Swap", type: "event",
    inputs: [
      { name: "projectId", type: "uint256", indexed: true  },
      { name: "user",      type: "address", indexed: true  },
      { name: "tokenIn",   type: "address", indexed: false },
      { name: "amountIn",  type: "uint256", indexed: false },
      { name: "tokenOut",  type: "address", indexed: false },
      { name: "amountOut", type: "uint256", indexed: false },
    ],
  },
] as const;

export const ERC20_ABI = [
  { name: "balanceOf",  type: "function", stateMutability: "view",       inputs: [{ name: "account", type: "address" }],                                              outputs: [{ type: "uint256" }] },
  { name: "allowance",  type: "function", stateMutability: "view",       inputs: [{ name: "owner",   type: "address" }, { name: "spender", type: "address" }],        outputs: [{ type: "uint256" }] },
  { name: "approve",    type: "function", stateMutability: "nonpayable", inputs: [{ name: "spender", type: "address" }, { name: "amount",  type: "uint256" }],        outputs: [{ type: "bool"    }] },
  { name: "transfer",   type: "function", stateMutability: "nonpayable", inputs: [{ name: "to",      type: "address" }, { name: "amount",  type: "uint256" }],        outputs: [{ type: "bool"    }] },
] as const;

export const ERC1155_ABI = [
  { name: "balanceOf",        type: "function", stateMutability: "view",       inputs: [{ name: "account",   type: "address" }, { name: "id",       type: "uint256" }], outputs: [{ type: "uint256" }] },
  { name: "totalSupplyByProject", type: "function", stateMutability: "view", inputs: [{ name: "projectId", type: "uint256" }], outputs: [{ type: "uint256" }] },
  { name: "isApprovedForAll", type: "function", stateMutability: "view",       inputs: [{ name: "account",   type: "address" }, { name: "operator", type: "address" }], outputs: [{ type: "bool"    }] },
  { name: "setApprovalForAll",type: "function", stateMutability: "nonpayable", inputs: [{ name: "operator",  type: "address" }, { name: "approved", type: "bool"    }], outputs: [] },
] as const;

export const REVENUE_ROUTER_ABI = [
  { name: "admin", type: "function", stateMutability: "view", inputs: [], outputs: [{ type: "address" }] },
  { name: "vault", type: "function", stateMutability: "view", inputs: [], outputs: [{ type: "address" }] },
  { name: "totalRevenueReceived", type: "function", stateMutability: "view", inputs: [], outputs: [{ type: "uint256" }] },
  { name: "totalCollected", type: "function", stateMutability: "view", inputs: [], outputs: [{ type: "uint256" }] },
  { name: "setVault", type: "function", stateMutability: "nonpayable", inputs: [{ name: "vault_", type: "address" }], outputs: [] },
  { name: "collect", type: "function", stateMutability: "nonpayable", inputs: [], outputs: [] },
  { name: "VaultAlreadySet", type: "error", inputs: [] },
  { name: "NotVault", type: "error", inputs: [] },
  {
    name: "RevenueReceived",
    type: "event",
    inputs: [
      { name: "amount", type: "uint256", indexed: false },
    ],
  },
  {
    name: "Collected",
    type: "event",
    inputs: [
      { name: "admin", type: "address", indexed: true },
      { name: "amount", type: "uint256", indexed: false },
    ],
  },
] as const;

export const MOCK_LENDER_ABI = [
  { name: "addYield", type: "function", stateMutability: "nonpayable", inputs: [], outputs: [] },
  { name: "supply", type: "function", stateMutability: "nonpayable", inputs: [{ name: "amount", type: "uint256" }], outputs: [] },
  { name: "balance", type: "function", stateMutability: "view", inputs: [], outputs: [{ type: "uint256" }] },
  { name: "yieldBalance", type: "function", stateMutability: "view", inputs: [], outputs: [{ type: "uint256" }] },
  { name: "YIELD_AMOUNT", type: "function", stateMutability: "view", inputs: [], outputs: [{ type: "uint256" }] },
] as const;

export const VAULT_ABI = [
  { name: "NotAdmin", type: "error", inputs: [] },
  { name: "NotProjectFounder", type: "error", inputs: [] },
  { name: "NotPendingAdmin", type: "error", inputs: [] },
  { name: "NotBacker", type: "error", inputs: [] },
  { name: "NotTreasury", type: "error", inputs: [] },
  { name: "BadAddress", type: "error", inputs: [] },
  { name: "BadProject", type: "error", inputs: [] },
  { name: "BadMilestones", type: "error", inputs: [] },
  { name: "BadDeadline", type: "error", inputs: [] },
  { name: "ZeroAmount", type: "error", inputs: [] },
  { name: "TransferFailed", type: "error", inputs: [] },
  { name: "ProjectNotTradable", type: "error", inputs: [] },
  { name: "ProjectComplete", type: "error", inputs: [] },
  { name: "ReleasePending", type: "error", inputs: [] },
  { name: "DeadlinePassed", type: "error", inputs: [] },
  { name: "DeadlineNotPassed", type: "error", inputs: [] },
  { name: "GoalWasMet", type: "error", inputs: [] },
  { name: "NothingToRefund", type: "error", inputs: [] },
  { name: "FundingGoalNotMet", type: "error", inputs: [] },
  { name: "NoLender", type: "error", inputs: [] },
  { name: "NoYield", type: "error", inputs: [] },
  { name: "MilestoneDone", type: "error", inputs: [] },
  { name: "NoMilestone", type: "error", inputs: [] },
  { name: "AlreadyRequested", type: "error", inputs: [] },
  { name: "VetoActive", type: "error", inputs: [] },
  { name: "AlreadyVetoed", type: "error", inputs: [] },
  { name: "AlreadyVoted", type: "error", inputs: [] },
  { name: "NotAMM", type: "error", inputs: [] },
  { name: "NoRequest", type: "error", inputs: [] },
  { name: "VetoWindowOver", type: "error", inputs: [] },
  { name: "VetoWindowNotOver", type: "error", inputs: [] },
  { name: "NotVetoed", type: "error", inputs: [] },
  { name: "NothingToRelease", type: "error", inputs: [] },
  { name: "ProjectNotApproved", type: "error", inputs: [] },
  { name: "isAdmin",      type: "function", stateMutability: "view", inputs: [{ name: "user", type: "address" }], outputs: [{ type: "bool" }] },
  { name: "admin",        type: "function", stateMutability: "view", inputs: [], outputs: [{ type: "address" }] },
  { name: "pendingAdmin", type: "function", stateMutability: "view", inputs: [], outputs: [{ type: "address" }] },
  { name: "projectCount", type: "function", stateMutability: "view", inputs: [], outputs: [{ type: "uint256" }] },
  { name: "totalRaised",  type: "function", stateMutability: "view", inputs: [], outputs: [{ type: "uint256" }] },
  { name: "projectSubmissionFee", type: "function", stateMutability: "view", inputs: [], outputs: [{ type: "uint256" }] },
  { name: "releaseFeeBps", type: "function", stateMutability: "view", inputs: [], outputs: [{ type: "uint256" }] },
  { name: "revenueRouter", type: "function", stateMutability: "view", inputs: [], outputs: [{ type: "address" }] },
  { name: "amm", type: "function", stateMutability: "view", inputs: [], outputs: [{ type: "address" }] },
  { name: "lender", type: "function", stateMutability: "view", inputs: [], outputs: [{ type: "address" }] },
  { name: "ammSeedBps", type: "function", stateMutability: "view", inputs: [], outputs: [{ type: "uint256" }] },
  { name: "setSubmissionFee", type: "function", stateMutability: "nonpayable", inputs: [{ name: "fee", type: "uint256" }], outputs: [] },
  { name: "setReleaseFeeBps", type: "function", stateMutability: "nonpayable", inputs: [{ name: "bps", type: "uint256" }], outputs: [] },
  { name: "setRevenueRouter", type: "function", stateMutability: "nonpayable", inputs: [{ name: "revenueRouter_", type: "address" }], outputs: [] },
  { name: "setAMM", type: "function", stateMutability: "nonpayable", inputs: [{ name: "amm_", type: "address" }], outputs: [] },
  { name: "setAmmSeedBps", type: "function", stateMutability: "nonpayable", inputs: [{ name: "bps", type: "uint256" }], outputs: [] },
  { name: "setLender", type: "function", stateMutability: "nonpayable", inputs: [{ name: "lender_", type: "address" }], outputs: [] },
  { name: "transferAdmin", type: "function", stateMutability: "nonpayable", inputs: [{ name: "newAdmin", type: "address" }], outputs: [] },
  { name: "approveProject", type: "function", stateMutability: "nonpayable", inputs: [{ name: "projectId", type: "uint256" }], outputs: [] },
  {
    name: "invest",
    type: "function",
    stateMutability: "nonpayable",
    inputs: [
      { name: "projectId", type: "uint256" },
      { name: "amount", type: "uint256" },
      { name: "proof", type: "bytes" },
    ],
    outputs: [],
  },
  {
    name: "createProject",
    type: "function",
    stateMutability: "nonpayable",
    inputs: [
      { name: "treasury_", type: "address" },
      { name: "milestoneCount_", type: "uint256" },
      { name: "name_", type: "string" },
      { name: "description_", type: "string" },
      { name: "additionalFilesUrl_", type: "string" },
      { name: "iconUrl_", type: "string" },
      { name: "metadataUri_", type: "string" },
      { name: "fundingGoal_", type: "uint256" },
      { name: "fundingDeadline_", type: "uint256" },
      { name: "milestoneWindow_", type: "uint256" },
    ],
    outputs: [{ name: "projectId", type: "uint256" }],
  },
  {
    name: "projects", type: "function", stateMutability: "view",
    inputs: [{ name: "projectId", type: "uint256" }],
    outputs: [
      { name: "founder",            type: "address"  },
      { name: "treasury",           type: "address"  },
      { name: "milestoneCount",     type: "uint256"  },
      { name: "totalRaised",        type: "uint256"  },
      { name: "totalReleased",      type: "uint256"  },
      { name: "currentMilestone",   type: "uint256"  },
      { name: "releaseRequestedAt", type: "uint256"  },
      { name: "releaseVetoed",      type: "bool"     },
      { name: "metadataUri",        type: "string"   },
      { name: "fundingGoal",        type: "uint256"  },
      { name: "fundingDeadline",    type: "uint256"  },
      { name: "approved",           type: "bool"     },
      { name: "name",               type: "string"   },
      { name: "description",        type: "string"   },
      { name: "additionalFilesUrl", type: "string"   },
      { name: "iconUrl",            type: "string"   },
      { name: "totalAmmSeeded",     type: "uint256"  },
      { name: "milestoneWindow",    type: "uint256"  },
      { name: "milestoneDeadline",  type: "uint256"  },
      { name: "timeoutActive",      type: "bool"     },
      { name: "timeoutOpenedAt",    type: "uint256"  },
      { name: "projectDead",        type: "bool"     },
      { name: "releaseApproved",    type: "bool"     },
    ],
  },
  {
    name: "getCommitmentBreakdown", type: "function", stateMutability: "view",
    inputs: [
      { name: "user",   type: "address" },
      { name: "offset", type: "uint256" },
      { name: "limit",  type: "uint256" },
    ],
    outputs: [
      { name: "projectIds", type: "uint256[]" },
      { name: "amounts",    type: "uint256[]" },
    ],
  },
  { name: "claimableYield", type: "function", stateMutability: "view",       inputs: [{ name: "user",      type: "address" }],                                                        outputs: [{ type: "uint256" }] },
  { name: "pendingYield",   type: "function", stateMutability: "view",       inputs: [{ name: "user",      type: "address" }],                                                        outputs: [{ type: "uint256" }] },
  { name: "yieldIndex",     type: "function", stateMutability: "view",       inputs: [],                                                                                              outputs: [{ type: "uint256" }] },
  { name: "harvestYield",   type: "function", stateMutability: "nonpayable", inputs: [],                                                                                              outputs: [] },
  { name: "claimYield",     type: "function", stateMutability: "nonpayable", inputs: [],                                                                                              outputs: [] },
  { name: "verifyNextMilestone", type: "function", stateMutability: "nonpayable", inputs: [{ name: "projectId", type: "uint256" }],                                                   outputs: [] },
  { name: "claimInitialMilestoneRelease", type: "function", stateMutability: "nonpayable", inputs: [{ name: "projectId", type: "uint256" }],                                          outputs: [] },
  { name: "seedAmmPool", type: "function", stateMutability: "nonpayable", inputs: [{ name: "projectId", type: "uint256" }],                                                           outputs: [] },
  { name: "requestRelease", type: "function", stateMutability: "nonpayable", inputs: [{ name: "projectId", type: "uint256" }],                                                        outputs: [] },
  { name: "executeRelease", type: "function", stateMutability: "nonpayable", inputs: [{ name: "projectId", type: "uint256" }],                                                        outputs: [] },
  { name: "clearVeto",      type: "function", stateMutability: "nonpayable", inputs: [{ name: "projectId", type: "uint256" }],                                                        outputs: [] },
  { name: "releasable",     type: "function", stateMutability: "view",       inputs: [{ name: "projectId", type: "uint256" }],                                                        outputs: [{ type: "uint256" }] },
  { name: "ammProjectReady", type: "function", stateMutability: "view",       inputs: [{ name: "projectId", type: "uint256" }],                                                        outputs: [{ type: "bool" }] },
  { name: "refund",         type: "function", stateMutability: "nonpayable", inputs: [{ name: "projectId", type: "uint256" }],                                                        outputs: [] },
  { name: "veto",           type: "function", stateMutability: "nonpayable", inputs: [{ name: "projectId", type: "uint256" }],                                                        outputs: [] },
  { name: "approveRelease", type: "function", stateMutability: "nonpayable", inputs: [{ name: "projectId", type: "uint256" }],                                                        outputs: [] },
  { name: "cancelVeto",    type: "function", stateMutability: "nonpayable", inputs: [{ name: "projectId", type: "uint256" }],                                                        outputs: [] },
  { name: "hasVoted",       type: "function", stateMutability: "view",       inputs: [{ name: "projectId", type: "uint256" }, { name: "user", type: "address" }],                     outputs: [{ type: "bool"    }] },
  { name: "hasApproved",    type: "function", stateMutability: "view",       inputs: [{ name: "projectId", type: "uint256" }, { name: "user", type: "address" }],                     outputs: [{ type: "bool"    }] },
  { name: "vetoVotes",      type: "function", stateMutability: "view",       inputs: [{ name: "projectId", type: "uint256" }],                                                        outputs: [{ type: "uint256" }] },
  { name: "triggerMilestoneTimeout", type: "function", stateMutability: "nonpayable", inputs: [{ name: "projectId", type: "uint256" }], outputs: [] },
  { name: "voteTimeout",    type: "function", stateMutability: "nonpayable", inputs: [{ name: "projectId", type: "uint256" }, { name: "extend", type: "bool" }], outputs: [] },
  { name: "executeTimeoutOutcome", type: "function", stateMutability: "nonpayable", inputs: [{ name: "projectId", type: "uint256" }], outputs: [] },
  { name: "claimTimeoutRefund",    type: "function", stateMutability: "nonpayable", inputs: [{ name: "projectId", type: "uint256" }], outputs: [] },
  { name: "claimVetoRefund",       type: "function", stateMutability: "nonpayable", inputs: [{ name: "projectId", type: "uint256" }], outputs: [] },
  { name: "timeoutVotesExtend", type: "function", stateMutability: "view", inputs: [{ name: "projectId", type: "uint256" }], outputs: [{ type: "uint256" }] },
  { name: "timeoutVotesRefund", type: "function", stateMutability: "view", inputs: [{ name: "projectId", type: "uint256" }], outputs: [{ type: "uint256" }] },
  { name: "hasVotedTimeout",    type: "function", stateMutability: "view", inputs: [{ name: "projectId", type: "uint256" }, { name: "user", type: "address" }], outputs: [{ type: "bool" }] },
  /* ─── events ─── */
  {
    name: "Invested", type: "event",
    inputs: [
      { name: "projectId", type: "uint256", indexed: true  },
      { name: "investor",  type: "address", indexed: true  },
      { name: "amount",    type: "uint256", indexed: false },
    ],
  },
  {
    name: "YieldClaimed", type: "event",
    inputs: [
      { name: "user",   type: "address", indexed: true  },
      { name: "amount", type: "uint256", indexed: false },
    ],
  },
  {
    name: "ProjectApproved", type: "event",
    inputs: [{ name: "projectId", type: "uint256", indexed: true }],
  },
  {
    name: "ReleaseRequested", type: "event",
    inputs: [
      { name: "projectId",   type: "uint256", indexed: true  },
      { name: "milestone",   type: "uint256", indexed: true  },
      { name: "requestedAt", type: "uint256", indexed: false },
    ],
  },
  {
    name: "FundsReleased", type: "event",
    inputs: [
      { name: "projectId", type: "uint256", indexed: true  },
      { name: "milestone", type: "uint256", indexed: true  },
      { name: "amount",    type: "uint256", indexed: false },
      { name: "treasury",  type: "address", indexed: false },
    ],
  },
  {
    name: "ReleaseApproved", type: "event",
    inputs: [
      { name: "projectId", type: "uint256", indexed: true },
      { name: "backer",    type: "address", indexed: true },
    ],
  },
  {
    name: "ReleaseApprovedThresholdMet", type: "event",
    inputs: [
      { name: "projectId", type: "uint256", indexed: true },
    ],
  },
  {
    name: "VetoedEvent", type: "event",
    inputs: [
      { name: "projectId", type: "uint256", indexed: true },
      { name: "by",        type: "address", indexed: true },
    ],
  },
  {
    name: "AmmSeeded", type: "event",
    inputs: [
      { name: "projectId", type: "uint256", indexed: true  },
      { name: "usdcIn",    type: "uint256", indexed: false },
      { name: "commitIn",  type: "uint256", indexed: false },
    ],
  },
  {
    name: "MilestoneTimeoutOpened", type: "event",
    inputs: [
      { name: "projectId", type: "uint256", indexed: true  },
      { name: "deadline",  type: "uint256", indexed: false },
    ],
  },
  {
    name: "TimeoutVoteCast", type: "event",
    inputs: [
      { name: "projectId", type: "uint256", indexed: true  },
      { name: "voter",     type: "address", indexed: true  },
      { name: "extend",    type: "bool",    indexed: false },
      { name: "stake",     type: "uint256", indexed: false },
    ],
  },
  {
    name: "TimeoutResolved", type: "event",
    inputs: [
      { name: "projectId", type: "uint256", indexed: true  },
      { name: "extended",  type: "bool",    indexed: false },
    ],
  },
] as const;
