// auto-generated by deploy.ts - do not edit manually
export const CONTRACTS = {
  USDC: "0x1c7D4B196Cb0C7B01d743Fbc6116a902379C7238" as `0x${string}`,
  TREASURY: "0x790cc683ba783866C16E349334A8f5A9fdaF1C22" as `0x${string}`,
  COMMIT: "0x5c903ceeb009c5b539e7B12a7D2230A48054bDD5" as `0x${string}`,
  LENDER: "0x3BB389f6d071197E43f0e00f7C69DEE210baFB39" as `0x${string}`,
  VAULT: "0x8A78955B6b07Ac699ed7dE6510CF37eBd622330c" as `0x${string}`,
  ROUTER: "0x1Ac948106F88Bb34fF5D5a72B0A4191925d49c78" as `0x${string}`,
  AMM: "0x7aCC50349a4d44A98FD1F0Bb6BC3eA60b6EE2b59" as `0x${string}`,
} as const;
