// auto-generated by deploy.ts - do not edit manually
export const CONTRACTS = {
  USDC: "0x1c7D4B196Cb0C7B01d743Fbc6116a902379C7238" as `0x${string}`,
  TREASURY: "0x790cc683ba783866C16E349334A8f5A9fdaF1C22" as `0x${string}`,
  COMMIT: "0x2126D6CEDb13A396CC72F7CfC9E0e06eDa294Da9" as `0x${string}`,
  LENDER: "0xBadc2aE18f1069057ad646c689a55a4E036989bE" as `0x${string}`,
  VAULT: "0xabDf915fdc7E04295Ca378003fD9A2E6bAAD72E4" as `0x${string}`,
  ROUTER: "0xd0b5b28c543C1Ebdf6f4d2D8914cC933464f931B" as `0x${string}`,
  AMM: "0x803E0F1394709B467AC055F6f00f9dB9B15EC068" as `0x${string}`,
} as const;
