// auto-generated by deploy.ts — do not edit manually
export const CONTRACTS = {
  USDC: "0x3459109957cD4BDC19F100ED9D6d703329B26CAE" as `0x${string}`,
  TREASURY: "0x790cc683ba783866C16E349334A8f5A9fdaF1C22" as `0x${string}`,
  COMMIT: "0xf4A3d61f12583B5580f042093E4cbAEB72e96D0d" as `0x${string}`,
  VAULT: "0x667bB28aA3e9382885A76c8893Bcd2a05B51498a" as `0x${string}`,
  ROUTER: "0x12452E65B93e8fe0D0c4eA55636d028C302df4E3" as `0x${string}`,
  AMM: "0x8cAD9636362dC69beaA36E39D8e58a9Bd79Ea75a" as `0x${string}`,
} as const;
